#define SPIEEPROM_SS_DDR	DDRD
#define SPIEEPROM_SS_PORT	PORTD
#define SPIEEPROM_SS		PD4

#define selectEEPROM()     cbi(SPIEEPROM_SS_PORT, SPIEEPROM_SS)
#define unselectEEPROM()   sbi(SPIEEPROM_SS_PORT, SPIEEPROM_SS)
