#ifndef SPIEEPROMCONF_H
#define SPIEEPROMCONF_H

#define SPIEEPROM_CS_DDR	DDRD
#define SPIEEPROM_CS_PORT	PORTD
#define SPIEEPROM_CS_PIN	4

#define selectEEPROM()     cbi(SPIEEPROM_CS_PORT, SPIEEPROM_CS_PIN)
#define unselectEEPROM()   sbi(SPIEEPROM_CS_PORT, SPIEEPROM_CS_PIN)

#endif
